### PR TITLE
Create MC Question Feature

### PR DESCRIPTION
**Pull request by MichaelPatsula**
This pull request contains the ability to create MC questions  #45. Users can create as many MC options as they want. The text of the MC options gets stored in the McOption table.

### CODE REVIEW

**Comment by MichaelPatsula** [comment]
Currently struggling with how to best persist the question info (https://www.baeldung.com/jackson-inheritance#2-per-class-annotations vs having two question wrappers for each of the Question subtypes)

**Comment by MichaelPatsula** [comment]
> Currently struggling with how to best persist the question info (I am not sure if I am doing it correctly). I am also not sure whether I should do per class annotations (https://www.baeldung.com/jackson-inheritance#2-per-class-annotations) or having multiple wrappers (for each subtype). Test cases also need to be made.

**Review by ChristopheTran — APPROVED** [review]
Looks good to me!

Just to clarify, text questions are now created in QuestionController.java instead of QuestionViewController.java (meaning the submitQuestion() can be removed right?)

**Review by ChristopheTran — CHANGES_REQUESTED** [review]
After testing it some more, I found that sometimes, I can't create a MC question since it says an MC option field is empty, even though I deleted all the autogenerated mc options.

It seems I'm able to create a MC if I don't delete the autogenerated mc options and just click submit. However, it also seems that it creates an a blank option (if I create two options, there's a third blank option).

**Comment by MichaelPatsula** [comment]
> Looks good to me!
> 
> Just to clarify, text questions are now created in QuestionController.java instead of QuestionViewController.java (meaning the submitQuestion() can be removed right?)

Yeah, the text questions are now created in QuestionController.java. I believe that the submitQuestion function can still be used if the browser doesn't allow JS. However, if the browser doesn't allow JS then they can't create MC questions.

**Comment by MichaelPatsula** [comment]
> After testing it some more, I found that when creating an MC question, the last option is not saved.

Thank you for finding this bug 💯 . I believe I have fixed it with commit f633145.

**Comment by RahulAnilkumar8** [comment]
I think this PR should be closed as the features was implemented in another PR.

**Pull request closed without merging**
