### PR TITLE
Rahul

### PR DESCRIPTION
**Pull request by RahulAnilkumar8**
This pull request contains the new survey creation/viewing pages and the hibernate backend for them.

### CODE REVIEW

**Comment by RahulAnilkumar8** [comment]
Please note that some of this code overlaps with Thomas' pull request. After that is merged to master, I will update my branch and push the changes again. But the code for my part is basically done. Will add more tests in a future pr

**Review by ChristopheTran — COMMENTED** [review]
Since we're now using ORM, shouldn't the Survey entity have a List of questions? 
How do we plan on doing the mappings?
I'm thinking each Survey has @OneToMany questions, and each question has @OneToMany answers.

**Comment by RahulAnilkumar8** [comment]
> 
> 
> Since we're now using ORM, shouldn't the Survey entity have a List of questions?
> How do we plan on doing the mappings?
> I'm thinking each Survey has OneToMany questions, and each question has OneToMany answers.

I didnt add this, primarily because this wasnt something I dealt with on my end for the parts I worked on. The questions part is being handled by @Christopher-Wang . I can add the data structures but I dont think it would have any impact on the other code written.

**Review by MichaelPatsula — APPROVED** [review]
Excellent! 🚀  

The view survey & create a survey page looks rlly good. The only comment I have is we may need a button for when a survey is closed to view the metrics of the survey.

**Comment by RahulAnilkumar8** [comment]
> 
> 
> Excellent! 🚀
> 
> The view survey & create a survey page looks rlly good. The only comment I have is we may need a button for when a survey is closed to view the metrics of the survey.

Ya I agree. I was thinking we can add that button in a later pr

**Review by ChristopheTran — APPROVED** [review]

**Review by Thomas-Leung — APPROVED** [review]

**Pull request merged**
